const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');
const W=800,H=600;
// Usa automaticamente o mesmo domínio onde o jogo foi hospedado.
// Não há localhost fixo no cliente, então Socket.IO funciona em Render, Railway, VPS etc.
const SERVER_URL=(window.PONG_SERVER_URL||location.origin).replace(/\/$/,'');
const socket=typeof io==='function'?io({ transports:['websocket','polling'] }):null;
const $=id=>document.getElementById(id); const screens=['home','online','waiting','result'];
let mode='menu', online=false, player=0, room=null, state={p1:250,p2:250,score1:0,score2:0,ball:{x:400,y:300,vx:7,vy:2},running:false};
let local={p1:250,p2:250,ball:{x:400,y:300,vx:7,vy:2},s1:0,s2:0}, botY=250, mouseY=250, keys={}; let particles=[]; let last=performance.now();
function screen(id){screens.forEach(x=>$(x).classList.toggle('active',x===id));}
function toast(t){const e=$('toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2200)}
function menu(){mode='menu';online=false;screen('home')}
function startLocal(vsBot){mode=vsBot?'bot':'local';online=false;local={p1:250,p2:250,ball:{x:400,y:300,vx:7,vy:Math.random()*5-2.5},s1:0,s2:0};}
function startOnline(){mode='onlineLobby';online=true;screen('online');if(socket)socket.emit('rooms:list')}
function resetOnlineState(){state={p1:250,p2:250,score1:0,score2:0,ball:{x:400,y:300,vx:7,vy:2},running:false}}
function drawBg(t){ctx.fillStyle='#03050a';ctx.fillRect(0,0,W,H);let g=ctx.createRadialGradient(400,280,20,400,300,500);g.addColorStop(0,'#111c31');g.addColorStop(1,'#03050a');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.strokeStyle='#ffffff08';for(let x=0;x<=W;x+=40){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=0;y<=H;y+=40){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}ctx.setLineDash([8,12]);ctx.strokeStyle='#35e7ff25';ctx.beginPath();ctx.moveTo(W/2,0);ctx.lineTo(W/2,H);ctx.stroke();ctx.setLineDash([])}
function glowRect(x,y,w,h,c){ctx.save();ctx.shadowColor=c;ctx.shadowBlur=18;ctx.fillStyle=c;ctx.roundRect(x,y,w,h,7);ctx.fill();ctx.restore()}
function drawGame(s){drawBg();ctx.fillStyle='#dbeeff';ctx.font='700 56px Orbitron';ctx.textAlign='center';ctx.globalAlpha=.8;ctx.fillText(s.score1,350,72);ctx.fillText(s.score2,450,72);ctx.globalAlpha=1;ctx.font='9px Space Mono';ctx.fillStyle='#65748c';ctx.fillText('FIRST TO 7',400,92);glowRect(24,s.p1,14,96,'#35e7ff');glowRect(762,s.p2,14,96,'#ff3c9e');for(const p of particles){ctx.globalAlpha=p.life;ctx.fillStyle=p.c;ctx.fillRect(p.x,p.y,3,3)}ctx.globalAlpha=1;ctx.save();ctx.shadowColor='#fff';ctx.shadowBlur=22;ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(s.ball.x,s.ball.y,9,0,Math.PI*2);ctx.fill();ctx.restore();if(!s.running){ctx.textAlign='center';ctx.font='700 14px Orbitron';ctx.fillStyle='#fff';ctx.fillText(online?'AGUARDANDO JOGADOR...':'CLIQUE PARA SACAR',400,310)}}
function localStep(dt){const speed=10;if(keys.w)local.p1=Math.max(20,local.p1-speed*dt);if(keys.s)local.p1=Math.min(484,local.p1+speed*dt);if(keys.ArrowUp)local.p2=Math.max(20,local.p2-speed*dt);if(keys.ArrowDown)local.p2=Math.min(484,local.p2+speed*dt);if(mode==='bot'){let target=local.ball.y-48;botY+=(target-botY)*Math.min(.07*dt,1);local.p2=botY}let b=local.ball;if(mode==='local'||mode==='bot'){b.x+=b.vx*dt;b.y+=b.vy*dt;if(b.y<10||b.y>590){b.vy*=-1;b.y=Math.max(10,Math.min(590,b.y))}if(b.x<45&&b.x>24&&b.y>local.p1-4&&b.y<local.p1+100&&b.vx<0){b.vx=Math.min(Math.abs(b.vx)*1.04+.12,15);b.vy+=(b.y-local.p1-50)/18;b.x=45;hit(b.x,b.y,'#35e7ff')}if(b.x>755&&b.x<776&&b.y>local.p2-4&&b.y<local.p2+100&&b.vx>0){b.vx=-Math.min(Math.abs(b.vx)*1.04+.12,15);b.vy+=(b.y-local.p2-50)/18;b.x=755;hit(b.x,b.y,'#ff3c9e')}if(b.x<-20){local.s2++;serve(local,1)}if(b.x>820){local.s1++;serve(local,-1)}}}
function serve(s,dir){if(s.s1>=7||s.s2>=7){const winner=s.s1>=7?'JOGADOR 1':'JOGADOR 2';$('winner').textContent=winner+' VENCEU';$('finalScore').textContent=`${s.s1} — ${s.s2}`;screen('result');mode='result';return}s.ball={x:400,y:300,vx:7*dir,vy:Math.random()*5-2.5}}
function hit(x,y,c){for(let i=0;i<10;i++)particles.push({x,y,vx:(Math.random()-.5)*4,vy:(Math.random()-.5)*4,life:1,c})}
function updateParticles(dt){particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=.045*dt});particles=particles.filter(p=>p.life>0)}
function frame(now){const dt=Math.min((now-last)/16.6667,2);last=now;updateParticles(dt);if(mode==='local'||mode==='bot')localStep(dt);if(mode==='local'||mode==='bot')drawGame({p1:local.p1,p2:local.p2,score1:local.s1,score2:local.s2,ball:local.ball,running:true});else if(mode==='onlineGame')drawGame(state);else drawBg();requestAnimationFrame(frame)}requestAnimationFrame(frame);
canvas.addEventListener('mousemove',e=>{const r=canvas.getBoundingClientRect(),y=(e.clientY-r.top)*H/r.height;mouseY=Math.max(20,Math.min(484,y-48));if(mode==='onlineGame'&&online&&socket)socket.emit('paddle:set',mouseY);else if(mode==='local'||mode==='bot'){if(mode==='local')local.p1=mouseY;else local.p2=mouseY}});
canvas.addEventListener('click',()=>{if(mode==='local'&&local.s1===0&&local.s2===0){} if(mode==='onlineGame'&&state.running===false&&socket&&room)socket.emit('match:restart')});
window.addEventListener('keydown',e=>{keys[e.key]=true;if(['ArrowUp','ArrowDown',' '].includes(e.key))e.preventDefault();if(e.key==='Escape'&&mode!=='menu')menu()});window.addEventListener('keyup',e=>keys[e.key]=false);
document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{const a=b.dataset.action;if(a==='home')menu();if(a==='local')startLocal(false);if(a==='bot')startLocal(true);if(a==='online')startOnline()});
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tabbody').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active')});
$('createBtn').onclick=()=>{if(!socket)return toast('Servidor offline');socket.emit('room:create',{code:$('roomCode').value,name:$('roomName').value,public:$('roomPublic').checked})};$('joinBtn').onclick=()=>{if(!socket)return toast('Servidor offline');socket.emit('room:join',$('joinCode').value)};$('refresh').onclick=()=>socket?.emit('rooms:list');$('leave').onclick=()=>{socket?.emit('room:leave');menu()};$('copy').onclick=()=>{navigator.clipboard?.writeText(location.origin+'/join/'+room);toast('Link copiado!')};$('again').onclick=()=>{if(online){socket?.emit('match:restart');mode='onlineGame';screen('online');document.getElementById('online').classList.remove('active')}else startLocal(false)};
function showWaiting(d){room=d.code;screen('waiting');$('waitingName').textContent=d.name;$('waitingCode').textContent=d.code;mode='waiting'}
if(socket){socket.on('connect',()=>{$('net').textContent='● ONLINE';$('net').className='net online'});socket.on('disconnect',()=>{$('net').textContent='● OFFLINE';$('net').className='net offline';if(online)toast('Conexão com o servidor perdida')});socket.on('rooms:update',list=>{$('roomsList').innerHTML=list.length?list.map(r=>`<div class="room"><span>${escapeHtml(r.name)}<br><small>${r.players}/2 • ${r.code}</small></span><button data-room="${r.code}">ENTRAR</button></div>`).join(''):'<span class="muted">Nenhuma sala disponível.</span>';document.querySelectorAll('[data-room]').forEach(b=>b.onclick=()=>socket.emit('room:join',b.dataset.room))});socket.on('room:created',d=>showWaiting(d));socket.on('room:joined',d=>{room=d.code;player=d.player});socket.on('room:error',m=>toast(m));socket.on('match:start',s=>{state=s;mode='onlineGame';online=true;screen('home');screens.forEach(x=>$(x).classList.remove('active'));toast(`Você é o Jogador ${player}`)});socket.on('state',s=>state=s);socket.on('match:over',d=>{$('winner').textContent=`JOGADOR ${d.winner} VENCEU`;$('finalScore').textContent=`${d.score1} — ${d.score2}`;mode='result';screen('result')});socket.on('room:closed',()=>{if(online){toast('A sala foi encerrada');menu()}})}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
if(socket && location.pathname.startsWith('/join/')){ const code=decodeURIComponent(location.pathname.split('/').pop()); startOnline(); setTimeout(()=>socket.emit('room:join',code),250); }
